'''This module contains custom schemas used in the project.'''
import enum


class EpisodeType(str, enum.Enum):
    """Enum to represent the type of episode"""
    MANGA_CANON = 'Manga Canon'
    FILLER = 'Filler'
    MIXED = 'Mixed Canon/Filler'

class Characters(str, enum.Enum):
    """Enum to represent the names of characters"""
    NARUTO_UZUMAKI = 'Naruto Uzumaki'
    SASUKE_UCHIHA = 'Sasuke Uchiha'
    ITACHI_UCHIHA = 'Itachi Uchiha'
    HATAKE_KAKASHI = 'Hatake Kakashi'
    JIRAYA = 'Jiraya'
    PAIN = 'Pain'
    OROCCHIMARU = 'Orochimaru'
    SAKURA_HARUNO = 'Sakura Haruno'
    INO_YAMANAKA = 'Ino Yamanaka'
    GAARA = 'Gaara'
    MIGHTY_GUY = 'Mighty Guy'
    ROCKE_LEE = 'Rocke Lee'
    NAGATO = 'Nagato'
    JIROBU = 'Jirobu'
    SHIKAKU_NARA = 'Shikaku Nara'
    ZABUZA_MOMOCHI = 'Zabuza Momochi'
    TOBIRAMA_SENJU = 'Tobirama Senju'
    SAI = 'Sai'
    GENMA_SHIRANUI = 'Genma Shiranui'
    TENTEN = 'Tenten'
    NEJI_HYUGA = 'Neji Hyuga'
    ANKO_MITARASHI = 'Anko Mitarashi'
    SASORI = 'Sasori'
    HINATA_HYUGA = 'Hinata Hyuga'
    TEMARI = 'Temari'
    GAMABUNTA = 'Gamabunta'
    IRUKA_UMINO = 'Iruka Umino'
    HIDAN = 'Hidan'
    OHNOKI = 'Ohnoki'
    DEIDARA = 'Deidara'
    KIBA_INUZUKA = 'Kiba Inuzuka'
    OBITO_UCHIHA = 'Obito Uchiha'
    KOBUTO_YAKUSHI = 'Kobuto Yakushi'
    HIRUZEN_SARUTOBI = 'Hiruzen Sarutobi'
    YASHAMARU = 'Yashamaru'
    NARA_SHIKAMARU = 'Nara Shikamaru'
    TOBI = 'Tobi'
    HAKU = 'Haku'
    CHOUJI_AKIMICHI = 'Chouji Akimichi'
    KIMIMARO = 'Kimimaro'
    KISAME_HOSHIGAKI = 'Kisame Hoshigaki'
    KANKURO = 'Kankuro'
    MAADARA_UCCHIHA = 'Maadara Uchiha'
    SHINO_ABURAME = 'Shino Aburame'
    TSUNADE = 'Tsunade'
    SHIMURA_DAZNO = 'Shimura Dazno'
    ONOKI = 'Ōnoki'
