name: Resume Yugabyte Cluster

on:
  schedule:
    - cron: '0 0 */14 * *' # Run at midnight every 15 days
  workflow_dispatch:

jobs:
  hit_api:
    runs-on: ubuntu-latest

    steps:
      - name: Hit API endpoint
        env:
          API_URL: ${{ secrets.API_URL }}
          ACCESS_TOKEN': ${{ secrets.YUGABYTE_TOKEN }}
        run: |
          curl $API_URL \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer $ACCESS_TOKEN'